//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEMS.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaryBankMapping
    {
        public int MappingId { get; set; }
        public string BenId { get; set; }
        public string BankCode { get; set; }
        public string BranchCode { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual BankBranch BankBranch { get; set; }
    }
}
