//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEMS.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        public int InspectionId { get; set; }
        public string BenId { get; set; }
        public int InspectionLevel { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> InspectedBy { get; set; }
        public Nullable<System.DateTime> InspectedDate { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<int> FileId { get; set; }
    }
}
