//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEMS.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Survey()
        {
            this.BeneficiaryDetails = new HashSet<BeneficiaryDetail>();
        }
    
        public int SurveyId { get; set; }
        public int OwnerId { get; set; }
        public string OwnerFirstName { get; set; }
        public string OwnerLastName { get; set; }
        public string GenderCode { get; set; }
        public string OwnerPhoneNumber { get; set; }
        public string DamageStatus { get; set; }
        public string FrontHousePhoto { get; set; }
        public string LeftHousePhoto { get; set; }
        public string RightHousePhoto { get; set; }
        public string BackHousePhoto { get; set; }
        public Nullable<int> SurveyedBy { get; set; }
        public Nullable<System.DateTime> SurveyedDate { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> PostCodeId { get; set; }
        public Nullable<int> FileId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneficiaryDetail> BeneficiaryDetails { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
